spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://ProductApp
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://UserApp
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: user-auth-service
          uri: lb://UserAuthService
          predicates:
            - Path=/auth/**
