spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter

        - id: user-auth-service
          uri: lb://UserAuthService
          predicates:
            - Path=/auth/**
